export const Guya = 'guya.moe'

export enum SiteType {
  Manganato = 'manganato.com',
  Webtoons = 'webtoons.com',
  LikeManga = 'likemanga.io',
  Mangakakalot = 'mangakakalot.com',
  MangaDex = 'mangadex.org',
  MangaKomi = 'mangakomi.io',
  LSComic = 'lscomic.com',
  HiperDEX = 'hiperdex.com',
  ReaperScans = 'reaperscans.com',
  AsuraScans = 'asuratoon.com',
  MangaTx = 'mangatx.com',
  Mangago = 'mangago.me',
  ZeroScans = 'zeroscans.com',
  Batoto = 'bato.to',
  FlameComics = 'flamecomics.com',
  ResetScans = 'reset-scans.com',
  BiliBiliComics = 'bilibilicomics.com',
  CosmicScans = 'cosmic-scans.com',
  Cubari = 'cubari.moe',
  LuminousScans = 'luminousscans.gg',
  Tapas = 'tapas.io',
  Comikey = 'comikey.com',
  Tappytoon = 'tappytoon.com',
  ScyllaScans = 'scyllascans.org',
}

export enum SiteName {
  'manganato.com' = 'Manganato',
  'webtoons.com' = 'Webtoons',
  'likemanga.io' = 'LikeManga',
  'mangakakalot.com' = 'Mangakakalot',
  'mangadex.org' = 'MangaDex',
  'mangakomi.io' = 'Manga Komi',
  'lscomic.com' = 'LS Comic',
  'hiperdex.com' = 'HiperDEX',
  'reaperscans.com' = 'Reaper Scans',
  'asuratoon.com' = 'Asura Scans',
  'mangatx.com' = 'MangaTx',
  'mangago.me' = 'Mangago',
  'kitsu.io' = 'Kitsu',
  'zeroscans.com' = 'Zero Scans',
  'bato.to' = 'Batoto',
  'flamecomics.com' = 'Flame Comics',
  'reset-scans.com' = 'Reset Scans',
  'bilibilicomics.com' = 'BiliBili Comics',
  'cosmic-scans.com' = 'Cosmic Scans',
  'cubari.moe' = 'Cubari / Guya',
  'luminousscans.gg' = 'Luminous Scans',
  'tapas.io' = 'Tapas',
  'comikey.com' = 'Comikey',
  'tappytoon.com' = 'Tappytoon',
  'scyllascans.org' = 'Scylla Scans',
}

export enum SiteState {
  OFFLINE = 'Site not reachable',
  INVALID = 'Visit to set cookies',
  REACHABLE = 'Reachable',
}
